[package]
name = "bevy_gizmos"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["nithinmuthukumar", "MrPicklePinosaur"]
description = ""
repository = "https://github.com/HalfPixelStudios/bevy_gizmos"

[dependencies]
bevy = { version = "0.8.0" }
